In [5]:
import pandas as pd

In [6]:
df=pd.read_csv("dataset_Facebook.csv",sep=';')

In [7]:
df

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [8]:
df.head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393

In [11]:
df1=df[["Type","Category","Post Month","Post Weekday","Post Hour"]]

In [12]:
df1

       Type  Category  Post Month  Post Weekday  Post Hour
0     Photo         2          12             4          3
1    Status         2          12             3         10
2     Photo         3          12             3          3
3     Photo         2          12             2         10
4     Photo         2          12             2          3
..      ...       ...         ...           ...        ...
495   Photo         3           1             7          2
496   Photo         2           1             5          8
497   Photo         1           1             5          2
498   Photo         3           1             4         11
499   Photo         2           1             4          4

[500 rows x 5 columns]

In [13]:
df2 = df[['Category','Paid','Post Weekday']]
df2

     Category  Paid  Post Weekday
0           2   0.0             4
1           2   0.0             3
2           3   0.0             3
3           2   1.0             2
4           2   0.0             2
..        ...   ...           ...
495         3   0.0             7
496         2   0.0             5
497         1   0.0             5
498         3   0.0             4
499         2   NaN             4

[500 rows x 3 columns]

In [14]:
sample=df.loc[10:50,["Type","Post Month"]]
sample

      Type  Post Month
10  Status          12
11   Photo          12
12   Photo          12
13   Photo          12
14   Photo          12
15  Status          12
16   Photo          12
17   Photo          12
18  Status          12
19   Photo          12
20   Photo          12
21   Photo          12
22    Link          12
23   Photo          12
24  Status          12
25  Status          12
26  Status          12
27   Photo          12
28   Photo          12
29   Video          12
30   Photo          12
31   Photo          12
32   Photo          12
33   Photo          12
34   Photo          12
35   Photo          12
36   Photo          12
37   Photo          12
38  Status          12
39   Photo          12
40  Status          12
41    Link          12
42   Photo          12
43    Link          12
44   Photo          12
45    Link          12
46  Status          12
47    Link          12
48   Photo          12
49    Link          12
50   Photo          11

In [16]:
sample2=df.iloc[10:20,2:5]

In [17]:
sample2

    Category  Post Month  Post Weekday
10         2          12             5
11         2          12             5
12         2          12             5
13         2          12             5
14         2          12             4
15         2          12             3
16         3          12             3
17         1          12             2
18         3          12             2
19         3          12             1

In [18]:
merge=pd.concat([df1,df2])

In [19]:
merge

       Type  Category  Post Month  Post Weekday  Post Hour  Paid
0     Photo         2        12.0             4        3.0   NaN
1    Status         2        12.0             3       10.0   NaN
2     Photo         3        12.0             3        3.0   NaN
3     Photo         2        12.0             2       10.0   NaN
4     Photo         2        12.0             2        3.0   NaN
..      ...       ...         ...           ...        ...   ...
495     NaN         3         NaN             7        NaN   0.0
496     NaN         2         NaN             5        NaN   0.0
497     NaN         1         NaN             5        NaN   0.0
498     NaN         3         NaN             4        NaN   0.0
499     NaN         2         NaN             4        NaN   NaN

[1000 rows x 6 columns]

In [22]:
sorted=df.sort_values(by='like',ascending=False)

In [23]:
sorted

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
244,130791,Photo,2,7,3,5,1.0,180480,319133,8072,4010,6242,108752,51456,3316,372,5172.0,790.0,6334
379,111620,Photo,3,4,1,14,1.0,105632,147918,3984,2254,3391,48575,27328,1936,51,1998.0,128.0,2177
349,117764,Photo,3,5,5,13,0.0,81856,124753,3000,1637,2718,52477,27392,1756,45,1639.0,122.0,1806
168,135428,Photo,1,9,3,10,0.0,41984,68290,3370,2420,4074,34802,20928,2126,144,1622.0,208.0,1974
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,137020,Photo,1,10,4,9,1.0,1357,2453,37,37,55,2154,1120,32,0,0.0,0.0,0
441,98195,Photo,1,3,5,4,1.0,1845,2670,9,9,9,1614,1008,9,0,0.0,0.0,0
76,137893,Photo,1,11,3,2,0.0,1228,2392,17,17,19,2392,1228,17,0,0.0,0.0,0
417,104070,Photo,1,3,3,10,0.0,1874,2474,25,25,31,1483,1062,15,0,0.0,0.0,0
111,136736,Photo,1,10,6,8,0.0,1261,2158,37,37,49,1911,1077,33,0,NaN,NaN,0

In [24]:
sorted= df.sort_values(by='like', ascending=True)
sorted

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
76,137893,Photo,1,11,3,2,0.0,1228,2392,17,17,19,2392,1228,17,0,0.0,0.0,0
100,137020,Photo,1,10,4,9,1.0,1357,2453,37,37,55,2154,1120,32,0,0.0,0.0,0
441,98195,Photo,1,3,5,4,1.0,1845,2670,9,9,9,1614,1008,9,0,0.0,0.0,0
417,104070,Photo,1,3,3,10,0.0,1874,2474,25,25,31,1483,1062,15,0,0.0,0.0,0
21,138414,Photo,1,12,7,10,0.0,1384,2467,15,15,20,2196,1172,15,0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,135428,Photo,1,9,3,10,0.0,41984,68290,3370,2420,4074,34802,20928,2126,144,1622.0,208.0,1974
349,117764,Photo,3,5,5,13,0.0,81856,124753,3000,1637,2718,52477,27392,1756,45,1639.0,122.0,1806
379,111620,Photo,3,4,1,14,1.0,105632,147918,3984,2254,3391,48575,27328,1936,51,1998.0,128.0,2177
244,130791,Photo,2,7,3,5,1.0,180480,319133,8072,4010,6242,108752,51456,3316,372,5172.0,790.0,6334
111,136736,Photo,1,10,6,8,0.0,1261,2158,37,37,49,1911,1077,33,0,NaN,NaN,0

In [25]:
transposed=df.head().transpose()

In [26]:
transposed

,0,1,2,3,4
Page total likes,139441,139441,139441,139441,139441
Type,Photo,Status,Photo,Photo,Photo
Category,2,2,3,2,2
Post Month,12,12,12,12,12
Post Weekday,4,3,3,2,2
Post Hour,3,10,3,10,3
Paid,0.0,0.0,0.0,1.0,0.0
Lifetime Post Total Reach,2752,10460,2413,50128,7244
Lifetime Post Total Impressions,5091,19057,4373,87991,13594
Lifetime Engaged Users,178,1457,177,2211,671
Lifetime Post Consumers,109,1361,113,790,410
Lifetime Post Consumptions,159,1674,154,1119,580
Lifetime Post Impressions by people who have liked your Page,3078,11710,2812,61027,6228
Lifetime Post reach by people who like your Page,1640,6112,1503,32048,3200
Lifetime People who have liked your Page and engaged with your post,119,1108,132,1386,396
comment,4,5,0,58,19
like,79.0,130.0,66.0,1572.0,325.0
share,17.0,29.0,14.0,147.0,49.0
Total Interactions,100,164,80,1777,393

In [27]:
df.shape

(500, 19)

In [31]:
new_df=pd.melt(df,id_vars='Post Month',value_vars='like')

In [32]:
new_df

     Post Month variable   value
0            12     like    79.0
1            12     like   130.0
2            12     like    66.0
3            12     like  1572.0
4            12     like   325.0
..          ...      ...     ...
495           1     like    53.0
496           1     like    53.0
497           1     like    93.0
498           1     like    91.0
499           1     like    91.0

[500 rows x 3 columns]

In [35]:
df_melted = pd.melt(df,
                    id_vars=['Page total likes', 'Type', 'Category', 'Post Month', 'Post Weekday', 'Post Hour', 'Paid'],
                    value_vars=['comment', 'like', 'share'],
                    var_name='Interaction Type',
                    value_name='Interaction Count')

In [36]:
df_melted

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Interaction Type,Interaction Count
0,139441,Photo,2,12,4,3,0.0,comment,4.0
1,139441,Status,2,12,3,10,0.0,comment,5.0
2,139441,Photo,3,12,3,3,0.0,comment,0.0
3,139441,Photo,2,12,2,10,1.0,comment,58.0
4,139441,Photo,2,12,2,3,0.0,comment,19.0
...,...,...,...,...,...,...,...,...,...
1495,85093,Photo,3,1,7,2,0.0,share,26.0
1496,81370,Photo,2,1,5,8,0.0,share,22.0
1497,81370,Photo,1,1,5,2,0.0,share,18.0
1498,81370,Photo,3,1,4,11,0.0,share,38.0
1499,81370,Photo,2,1,4,4,NaN,share,28.0